name: spoc_venv
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - blas
  - bottleneck
  - c-ares
  - ca-certificates
  - h5py
  - hdf5
  - joblib
  - krb5
  - ld_impl_linux-64
  - libcurl
  - libedit
  - libev
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - libnghttp2
  - libssh2
  - libstdcxx-ng
  - lz4-c
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - numexpr
  - numpy
  - openssl
  - pandas
  - pip
  - pybind11-abi
  - python
  - python-dateutil
  - python-tzdata
  - pytz
  - readline
  - scikit-learn
  - scipy
  - setuptools
  - six
  - sqlite
  - tbb
  - threadpoolctl
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
    - biopython
